<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0+
 * @link    http://my.studiopress.com/themes/genesis/
 */

do_action( 'genesis_doctype' ); 
do_action( 'genesis_title' );
do_action( 'genesis_meta' );

wp_head(); //* we need this for plugins
?><!-- <meta name="viewport" content="width=device-width, initial-scale=1.0"> -->
<meta name = "format-detection" content = "telephone=no" />
<link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,300,400,600,700,800' rel='stylesheet' type='text/css'>
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
<script src="<?php echo get_stylesheet_directory_uri(); ?>/js/jquery.bxslider.min.js"></script>
<link href="<?php echo get_stylesheet_directory_uri(); ?>/lib/jquery.bxslider.css" rel="stylesheet" />
<script src="<?php echo get_stylesheet_directory_uri(); ?>/js/jquery.flexslider.js"></script>
<link href="<?php echo get_stylesheet_directory_uri(); ?>/css/flexslider.css" rel="stylesheet" />
<script src="<?php echo get_stylesheet_directory_uri(); ?>/js/jquery.matchHeight.js" type="text/javascript"></script>
<link rel="stylesheet" href="<?php echo get_stylesheet_directory_uri(); ?>/jquery-ui/css/no-theme/jquery-ui-1.10.4.custom.css">

<link rel="stylesheet" href="<?php echo get_stylesheet_directory_uri(); ?>/js/sidr/stylesheets/jquery.sidr.dark.css">

<script src="<?php echo get_stylesheet_directory_uri(); ?>/js/sidr/jquery.sidr.min.js"></script>
<script src="<?php echo get_stylesheet_directory_uri(); ?>/jquery-ui/js/jquery-ui-1.10.4.custom.js"></script>
<script type="text/javascript">
	  $(function() {
	    $( "#tabs,#tabs2" ).tabs();
	     $('.rgc-featured-image').matchHeight();
   	  });

	  jQuery(document).ready(function($){
	     
	  	  $('span.gfield_required').remove();
	  	  var numberOfImages = $('#home-slider .bxslider li').length;

		  if( numberOfImages > 1 ) {
			  $('.bxslider').bxSlider({
			  	autoStart:true,
			  	auto:true,
			  	mode:'fade',
			  	pager:false,
			  	controls:true
			  });
		  }
		  $('.excerpt span, .content p,#paper-primary h4, #paper-primary h1, #paper-primary h2, #paper-primary h3,.article-section ul,.article-section li').removeAttr('style');  
		  
		});
	</script>

	<script src="<?php echo get_stylesheet_directory_uri(); ?>/js/bbq.js"></script>
	<script src="<?php echo get_stylesheet_directory_uri(); ?>/js/custom.js"></script>
	<script type="text/javascript" src="<?php bloginfo( 'stylesheet_directory' ); ?>/fancybox/lib/jquery-1.8.2.min.js"></script>
	<script type='text/javascript'>var $fb = jQuery.noConflict();</script>
	
	<script type="text/javascript" src="<?php bloginfo( 'stylesheet_directory' ); ?>/fancybox/source/jquery.fancybox.js?v=2.1.3"></script>
	<link rel="stylesheet" type="text/css" href="<?php bloginfo( 'stylesheet_directory' ); ?>/fancybox/source/jquery.fancybox.css?v=2.1.2" media="screen" />
 	<script type="text/javascript" src="<?php bloginfo( 'stylesheet_directory' ); ?>/fancybox/source/jquery.fancybox-media.js"></script>
 	<script type="text/javascript">
 	<?php 
 	$classes = get_body_class();
 	if ( is_plugin_active('advanced-custom-fields/acf.php') ) {
		if (get_field('featured_vimeo_id')&&'issue'==get_post_type()) { ?>
		 	$fb(window).load(function() {
		 		$fb('.fancybox-media').trigger( "click" );
		 	});
		<?php }

	} ?>
	$fb(document).ready(function() {
		$fb(".fancybox").fancybox({
			'nextEffect': 'fade',
    		'prevEffect': 'fade',
			openEffect	: 'elastic',
			closeEffect	: 'elastic',
			beforeShow: function () {
			    this.title = (this.title ? '' + this.title + '<br />' : '') + 'Image ' + (this.index + 1) + ' of ' + this.group.length;
			}
		});

		$fb(".various").fancybox({
			fitToView	: false,
			width		: '325',
			height		: '555',
			autoSize	: false,
			closeClick	: false,
			openEffect	: 'elastic',
			closeEffect	: 'elastic',
			padding: [20,5,20,30],
			helpers : {
				/*overlay : {
		            css : {
		                'background' : 'rgba(255, 255, 255, 0.80)'
		            }
		        }*/
		    },
		    beforeShow: function(){
			  $(".fancybox-skin").css("backgroundColor","white");
			}
		});

		$fb('.fancybox-media').fancybox({
			openEffect  : 'none',
			closeEffect : 'none',
			maxHeight: 455, 
			maxWidth: 810,
			padding:0,
			closeBtn: true,
			closeClick : false,
			helpers : {
				media : {},
				overlay : {
					closeClick: false,
		            css : {
		                'background' : 'rgba(255, 255, 255, 1)'
		            }
		        }
			}
			,
			tpl:  { 
				closeBtn : '<a title="Skip" class="fancybox-item fancybox-close" href="javascript:;">Skip</a>'
		    }
		});

		$fb(".iframe").fancybox({
			maxWidth	: 340,
			maxHeight	: 900,
			fitToView	: false,
			width		: '70%',
			//height		: '70%',
			autoSize	: false,
			closeClick	: false,
			openEffect	: 'none',
			closeEffect	: 'none',
			scrolling	: 'no',
			scrollOutside: false
		});
	});
	</script>
</head>
<?php
genesis_markup( array(
	'html5'   => '<body %s>',
	'xhtml'   => sprintf( '<body class="%s">', implode( ' ', get_body_class() ) ),
	'context' => 'body',
) );
do_action( 'genesis_before' );

genesis_markup( array(
	'html5'   => '<div %s>',
	'xhtml'   => '<div id="wrap">',
	'context' => 'site-container',
) );

do_action( 'genesis_before_header' );
do_action( 'genesis_header' );
do_action( 'genesis_after_header' );

genesis_markup( array(
	'html5'   => '<div %s>',
	'xhtml'   => '<div id="inner">',
	'context' => 'site-inner',
) );
genesis_structural_wrap( 'site-inner' );

//edit